[package]
name = "nwind"
version = "0.1.0"
authors = ["Jan Bujak <jan.bujak@nokia.com>"]

[dependencies]
byteorder = "1"
gimli = "0.15"
goblin = "0.0.14"
scroll = "0.8"
memmap = "0.6"
regex = "0.2"
lazy_static = "1"
log = "0.4"
speedy = "0.4"
speedy-derive = "0.3"

[dev-dependencies]
env_logger = "0.5"
