[package]
name = "nwind"
version = "0.1.0"
authors = ["Jan Bujak <jan.bujak@nokia.com>"]

[dependencies]
byteorder = "1"
gimli = "0.16"
goblin = "0.0.14"
scroll = "0.8"
memmap = "0.6"
log = { version = "0.4", optional = true }
speedy = "0.4"
speedy-derive = "0.3"
lru = "0.1"
string-interner = "0.6"

[build-dependencies]
cc = { version = "1", optional = true }

[dev-dependencies]
env_logger = "0.5"

[features]
default = ["logging"]
local-unwinding = ["cc"]
logging = ["log"]
